# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 指尖二战
# Description of the Site
description: 文字策略游戏,更加有趣!
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: 家园二战, 指尖二战, 文字二战, 风云二战,文字策略游戏,SLG,战争游戏
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/morning.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 1923244321@gmail.com
facebook_username: ""
twitter_username: ""
instagram_username: ""
linkedin_username: ""
github_username:  ""
youtube_channel_id: ""
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: ""

# Disqus
disqus-shortname: ""

# Name of the Author
author-name: neoyuan
# URL for the Image of the Author
author-image: /assets/images/header.png
# 60 Words About the Author
author-about: 独立游戏开发者 二战游戏、文字游戏、策略卡牌游戏欢迎来聊
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/yuanshuli11

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
